# docker-compose.yaml to run this project in development mode

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "3000:3000"
        environment:
            - DATABASE_URL=postgresql://postgres:postgres@db:5432/postgres
            # - REDIS_URL=redis://redis:6379
            - NODE_ENV=development
            - PORT=3000
        volumes:
            - .:/app
            - /app/node_modules
        depends_on:
            - db

    db:
        image: postgres:14
        environment:
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
        ports:
            - "5432:5432"
        volumes:
            - postgres_data:/var/lib/postgresql/data

volumes:
    postgres_data: