import type { Venue } from "./types"

export const campusVenues: Venue[] = [
  {
    id: "campus-cafe",
    name: "Campus Café",
    type: "cafe",
    description: "The main campus coffee shop with great WiFi and study atmosphere",
    features: ["wifi", "food", "outlets", "moderate-noise"],
    rating: 4.5,
    location: "Student Center, Ground Floor",
    hours: "7:00 AM - 10:00 PM",
    atmosphere: "moderate",
    capacity: "large",
  },
  {
    id: "library-quiet-zone",
    name: "Library Quiet Study Area",
    type: "library",
    description: "Perfect for focused study sessions and academic discussions",
    features: ["wifi", "quiet", "outlets", "study-friendly"],
    rating: 4.8,
    location: "Main Library, 2nd Floor",
    hours: "6:00 AM - 12:00 AM",
    atmosphere: "quiet",
    capacity: "medium",
  },
  {
    id: "library-collaboration",
    name: "Library Collaboration Pods",
    type: "library",
    description: "Small group study rooms perfect for project discussions",
    features: ["wifi", "private", "whiteboard", "outlets"],
    rating: 4.7,
    location: "Main Library, 3rd Floor",
    hours: "6:00 AM - 12:00 AM",
    atmosphere: "quiet",
    capacity: "small",
  },
  {
    id: "student-lounge",
    name: "Student Center Lounge",
    type: "dining",
    description: "Casual meeting space with comfortable seating and snacks",
    features: ["wifi", "food", "comfortable-seating", "group-friendly"],
    rating: 4.2,
    location: "Student Center, 2nd Floor",
    hours: "8:00 AM - 11:00 PM",
    atmosphere: "lively",
    capacity: "large",
  },
  {
    id: "outdoor-courtyard",
    name: "Science Building Courtyard",
    type: "outdoor",
    description: "Beautiful outdoor space perfect for casual conversations",
    features: ["outdoor", "scenic", "fresh-air"],
    rating: 4.3,
    location: "Science Building Courtyard",
    hours: "Sunrise - Sunset",
    atmosphere: "quiet",
    capacity: "medium",
  },
  {
    id: "cs-lounge",
    name: "Computer Science Lounge",
    type: "study-room",
    description: "Department lounge with tech-focused atmosphere",
    features: ["wifi", "outlets", "whiteboards", "tech-friendly"],
    rating: 4.4,
    location: "Computer Science Building, 1st Floor",
    hours: "7:00 AM - 11:00 PM",
    atmosphere: "moderate",
    capacity: "medium",
  },
  {
    id: "grad-commons",
    name: "Graduate Student Commons",
    type: "study-room",
    description: "Exclusive space for graduate students with kitchen facilities",
    features: ["wifi", "kitchen", "quiet", "grad-only"],
    rating: 4.6,
    location: "Graduate Center, 2nd Floor",
    hours: "24/7 (Grad Students Only)",
    atmosphere: "quiet",
    capacity: "medium",
  },
  {
    id: "bookstore-cafe",
    name: "Bookstore Café",
    type: "cafe",
    description: "Cozy café inside the campus bookstore with literary vibes",
    features: ["wifi", "food", "books", "cozy"],
    rating: 4.1,
    location: "Campus Bookstore",
    hours: "8:00 AM - 8:00 PM",
    atmosphere: "quiet",
    capacity: "small",
  },
]

export const coffeeChatPurposes = [
  {
    id: "casual",
    label: "Casual Chat",
    description: "Get to know each other over coffee",
    icon: "☕",
    suggestedDuration: 60,
  },
  {
    id: "study",
    label: "Study Session",
    description: "Work on assignments or study together",
    icon: "📚",
    suggestedDuration: 120,
  },
  {
    id: "project",
    label: "Project Collaboration",
    description: "Discuss potential projects or collaborations",
    icon: "🚀",
    suggestedDuration: 90,
  },
  {
    id: "book-discussion",
    label: "Book Discussion",
    description: "Chat about books and reading recommendations",
    icon: "📖",
    suggestedDuration: 75,
  },
  {
    id: "networking",
    label: "Networking",
    description: "Professional networking and career discussions",
    icon: "🤝",
    suggestedDuration: 45,
  },
]
